### ISSUE TITLE
AudioBufferSourceNode

### ISSUE THREAD

**Issue by Larpoux** [xioxin/lab_sound_flutter#4]
Hi everybody.
I have a stupid question : 
How can I create an [AudioBufferSourceNode](https://api.dart.dev/stable/2.15.1/dart-web_audio/AudioBufferSourceNode-class.html) ?
Is there somewhere a table with how the W3C recommandation match the LabSound_flutter library?
Thank you guys /girls and others. Take care.

**Comment by Larpoux** [comment]
Hi @xioxin ,

Could you look to [this issue](https://github.com/LabSound/LabSound/issues/172) and tell us what you will do for that ?
Thank you

**Comment by xioxin** [comment]
AudioSampleNode is similar to it. You can have a try.

**Comment by Larpoux** [comment]
Thank you @xioxin
