### ISSUE TITLE
Example project gives error: "Failed to lookup symbol 'InitDartApiDL':  dlsym(RTLD_DEFAULT, InitDartApiDL): symbol not found"

### ISSUE THREAD

**Issue by yasinarik** [xioxin/lab_sound_flutter#6]
Hi @xioxin . Thanks for resolving my previous `flutter pub get` issue. 

I am having another difficulty so I opened this dedicated issue here.
Currently, I am trying the example project on the iOS simulator. However, all the example pages of the app give this error:

```
Unhandled Exception: Invalid argument(s): Failed to lookup symbol 'InitDartApiDL': 
dlsym(RTLD_DEFAULT, InitDartApiDL): symbol not found

#0      DynamicLibrary.lookup (dart:ffi-patch[/ffi_dynamic_library_patch.dart:34:70]())
dart-lang/ffi#1      LabSoundBind._InitDartApiDL_ptr
package:lab_sound_flutter[/src/generated_bindings.dart]():933
dart-lang/ffi#2      LabSoundBind._InitDartApiDL_ptr (package:lab_sound_flutter[/src/generated_bindings.dart]())
package:lab_sound_flutter/src/generated_bindings.dart:1
dart-lang/ffi#3      LabSoundBind._InitDartApiDL
package:lab_sound_flutter/src/generated_bindings.dart:935
dart-lang/ffi#4      LabSoundBind._InitDartApiDL (package:lab_sound_flutter/src/generated_bindings.dart)
package:lab_sound_flutter/src/generated_bindings.dart:1
dart-lang/ffi#5      LabSoundBind.InitDartApiDL
package:lab_sound_flutter/src/generated_bindings.dart:927
dart-lang/ffi#6      new LabSound._
package:lab_sound_flutter/…/lab_sound/lab_sound.dart:167
dart-lang/ffi#7      LabSound._sharedInstance
package:lab_sound_flutter/…/lab_sound/lab_sound.dart:327
dart-lang/ffi#8      new LabSound
package:lab_sound_flutter/…/lab_sound/lab_sound.dart:323
dart-lang/ffi#9   <…>
```

**Comment by yasinarik** [comment]
#### This might help you figure it out:
Searched the net for `Failed to lookup symbol` and I have encountered something like that:
 - (https://github.com/dart-lang/native/issues/897)

This is might be a similar problem. I changed the `Strip Style` as told. However, I couldn't find a solution.

**Comment by xioxin** [comment]
Sorry this was a mistake on my part. I checked and found that the macOS & iOS binaries were not properly committed to git.

To ensure that `flutter pub get` can be updated correctly, you can specify ref
```
  lab_sound_flutter:
    git:
      url: https://github.com/xioxin/lab_sound_flutter.git
      ref: 656b23d
```

You can also check `pubspec.lock` to make sure the version is correct

**Comment by yasinarik** [comment]
Thank you for your assistance & time. It is working now. Closing the issue.
